### ISSUE TITLE
configured supervisord, but not running

### ISSUE THREAD

**Issue by anksharm** [gwu-libraries/social-feed-manager#240]
We have supervsiord configured, and if its not running ( assuming someone has it in stop mode for some time), then SFM doesnt allow admin users to add/modify Twitter-filters. 
It throws an exception of "socket.py" file not found. 
Need to add an exception handling in that.

**Comment by anksharm** [comment]
@kerchner pushed a branch and created a pull request.

**Comment by kerchner** [comment]
Referenced pull request is #339 (which also addresses issue #338)
