### ISSUE TITLE
Filterstream not handling boolean query properly

### ISSUE THREAD

**Issue by anksharm** [gwu-libraries/social-feed-manager#258]
Twitter API for filterstream , for track works with boolean operation on the keyworks it needs to track. 

By this model, you can think of commas as logical ORs, while spaces are equivalent to logical ANDs (e.g. ‘the twitter’ is the AND twitter, and ‘the,twitter’ is the OR twitter).

this rule is not handled in the filterstream in SFM , 
for instance, a filter having the keyword as 'HP IBM' , 'Apple IBM'
should form a list as set([u'Apple IBM'  , u'IBM HP'])
instead forms a list as: 
         set([u'Apple', u'IBM', u'HP,'])

**Comment by kerchner** [comment]
ALSO:
- Validate locations.  Should match format of geo bounding box - 4 comma-separated decimal values; each value is >= -180.0 and <=180.0
- Migration should create a log file noting "people" values that could not be validated with twitter.  Do not remove the values; just log.
- clean/validation method when saving a TwitterFilter should raise a soft warning if one or more of the people values doesn't validate with Twitter (but allow saving to proceed).

**Comment by kerchner** [comment]
Also:   Replace any ```\r``` (line break) characters with a space - this applies to words and people.

**Comment by anksharm** [comment]
@kerchner people field works for most of the scenarios discussed. But it also accepts one expression which it should not : 'a, b z'  -- this should raise an error to put in comma.
