### ISSUE TITLE
supercharged fetch_tweets_by_id

### ISSUE THREAD

**Issue by edsu** [gwu-libraries/social-feed-manager#260]
I believe that the `fetch_tweets_by_id` management command could be made even better by changing the [tweepy.get_status](https://github.com/gwu-libraries/social-feed manager/blob/master/sfm/ui/management/commands/fetch_tweets_by_id.py#L41) all to instead use Twitter's  [statuses/lookup](https://dev.twitter.com/docs/api/1.1/get/statuses/lookup) API call. This would let you get 100 tweets for the price of just one request.

Currently one access token is limited to roughly 720 requests per hour (180 every 15 minutes). So instead of just being able to get 720 tweets per hour you could get 7,2000. It looks like tweepy might  [support](http://docs.tweepy.org/en/latest/api.html#API.statuses_lookup) status/lookup too.

**Comment by kerchner** [comment]
@justinlittman I would recommend rebasing this branch.

**Comment by justinlittman** [comment]
@kerchner Done I think.

**Comment by kerchner** [comment]
Fixed by https://github.com/gwu-libraries/social-feed-manager/pull/287
