### ISSUE TITLE
No module named urls

### ISSUE THREAD

**Issue by jackiekazil** [gwu-libraries/social-feed-manager#306]
When I tried to set up the project using master, I am getting the following error: 
```
Traceback:
File "/Users/jacquelinekazil/Projects/envs/sfm/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  99.                 resolver_match = resolver.resolve(request.path_info)
File "/Users/jacquelinekazil/Projects/envs/sfm/lib/python2.7/site-packages/django/core/urlresolvers.py" in resolve
  337.             for pattern in self.url_patterns:
File "/Users/jacquelinekazil/Projects/envs/sfm/lib/python2.7/site-packages/django/core/urlresolvers.py" in url_patterns
  365.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/Users/jacquelinekazil/Projects/envs/sfm/lib/python2.7/site-packages/django/core/urlresolvers.py" in urlconf_module
  360.             self._urlconf_module = import_module(self.urlconf_name)
File "/Users/jacquelinekazil/Projects/envs/sfm/lib/python2.7/site-packages/django/utils/importlib.py" in import_module
  40.         __import__(name)

Exception Type: ImportError at /
Exception Value: No module named urls
```

Full traceback: http://dpaste.com/04YC3SB

This isn't really helpful to troubleshoot. Suggestions?

**Comment by kerchner** [comment]
Hi Jackie,

Questions:

1.  What step in the setup results in the trace you pasted/linked?

2.  When you are in your activated virtualenv, what do you get when you
execute "pip freeze" ?

- Dan K.








*Dan KerchnerSenior Software Developer, Scholarly Technology GroupThe
George Washington University LibrariesGelman Library2130 H Street,
NWWashington, DC 20052202-994-7947 <202-994-7947>kerchner@gwu.edu
<kerchner@gwu.edu>*

**Comment by jackiekazil** [comment]
1. ./manage.py runserver
2. 
```
Django==1.6.10
django-queryset-iterator==0.1.1
django-social-auth==0.7.28
gnureadline==6.3.3
httplib2==0.9
ipython==2.4.0
lxml==3.4.1
meld3==1.0.0
oauth2==1.5.211
oauthlib==0.7.2
psycopg2==2.5.4
python-openid==2.2.5
pytz==2014.10
requests==2.5.1
requests-oauthlib==0.4.1
six==1.7.3
South==1.0.2
supervisor==3.1.3
tweepy==3.2.0
xlwt==0.7.5
```

**Comment by kerchner** [comment]
Hi @jackiekazil - Just today I created and am testing a solution #304, as I
noted that tweepy 3.2.0 breaks a couple of things in SFM.  It's our mistake
for not pinning the version in requirements.txt sooner.

However, this makes me concerned that other versions may also be untested
with SFM, so let's start with a few key packages:   Can you update your
requirements file so to pin the versions of django, requests, and tweepy?

django==1.6.8
django-social-auth
lxml
psycopg2
pytz
requests==2.4.3
south
tweepy=2.3.0
supervisor
xlwt
django-queryset-iterator

Did you previously have the latest tagged release, m5_002, working?

Anyway, I don't know if this is the issue, but let's start here.

- Dan

**Comment by kerchner** [comment]
@jackiekazil another potential difference is that we're running in Python 2.7.3 whereas you're at 2.7.9.

**Comment by jackiekazil** [comment]
I was running master, not m5_002.... so that could be a problem.
Should I try to m5_002 or continue w/ master?

**Comment by kerchner** [comment]
Up to you - are you looking to just get a running instance, or are you looking to work with the code?  Either way, my initial hunch is that we should at least try to line up versions of the key Python packages.

And another question - which version of the OS are you running in?

**Comment by jackiekazil** [comment]
OSX 10.9.5

So, I got replaced wait was in the requirements file and rebuild the env with what you sent (minus the typo :-)). 

YAY! It worked!

**Comment by kerchner** [comment]
Great!  So glad that it worked for you.  Please keep us posted with further questions.  I'll open a ticket and reference this one, as it is definitely a key data point... and motivator! :-)

**Comment by jackiekazil** [comment]
Sounds good. :-)
