### ISSUE TITLE
typo in documentation for stream mgmt commands

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/social-feed-manager#314]
Code examples for streamsample and filterstream commands on [read-the-docs] (http://social-feed-manager.readthedocs.org/en/m5_002/mgmt_commands.html#streamsample) show the save flag with one hyphen instead of two.  I believe it should be --save not -save.

**Comment by kerchner** [comment]
Reopening - when viewed on the readthedocs site, two hyphens are still being rendered as one.  (This does not happen in the local preview of /docs)
