### ISSUE TITLE
filterstream process stops writing

### ISSUE THREAD

**Issue by edsu** [gwu-libraries/social-feed-manager#316]
I changed the `SAVE_INTERVAL_SECONDS` to be 86400 (24 hours) so that my `DATA_DIR` wouldn't need to be cleaned up so often. Things appeared to work for three days but then the filterstream processes stopped writing to `DATA_DIR`.  The filterstream management commands were running, but appeared to be consuming a lot of CPU.

Has anyone else noticed behavior like this?  Was SAVE_INTERVAL_SECONDS set to 15 minutes to avoid something like this happening? 

I didn't see anything unusual in my supervisor.log, just that the processes started up ok:

```
2015-02-20 02:31:25,221 INFO success: twitterfilter-2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-20 02:31:25,221 INFO success: twitterfilter-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-20 02:31:25,221 INFO success: twitterfilter-4 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-20 10:28:15,417 INFO spawned: 'twitterfilter-5' with pid 30045
2015-02-20 10:28:16,424 INFO success: twitterfilter-5 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Any advice/tips you could provide would be appreciated. FWIW, the twitterfilter-5 filterstream was archiving about 300k tweets per day, for three days before all the filterstreams went into limbo.

**Comment by dchud** [comment]
The 15 minute default was largely a hunch.  The zipped-by-default strategy is flawed in that we don't handle problems well; if the process is interrupted a file may be corrupted because the zipped file isn't closed properly (see also #171).  Because streams can be and are interrupted for any number of accidental (network outage) or API-defined (another stream is started with same credentials) reasons it seemed like dropping the interval to something smallish seemed like a good way to limit the potential damage.  Also allows friendly parallel processing, though that's not much of an argument.

It seems likely that we'll want to pipeline activities like saving streamed data to disk, chopping up or aggregating files, compression, and others like these in future releases.

Aside from wanting to discuss this with you some more, do you want to suggest any specific changes?

**Comment by edsu** [comment]
Thanks @dchud. I haven't looked at the code closely. Does the filterstream API request to Twitter get closed and then reopened when the interval is up? It has been a lot more stable now that I'm using a 15 minute interval. I don't have any specific changes to request, so I think this can be closed as long as you know at least one person had a problem with a larger interval.

**Comment by dchud** [comment]
No, ```RotatingFile``` (https://github.com/gwu-libraries/social-feed-manager/blob/master/sfm/ui/models.py#L49) does not close the stream between file opens/closes. I guess I'm the original person who had a problem with not having a smallish interval. :)

Reviewing that code there's an option on whether to compress the files.  We could add a boolean config setting to make that optional, then longer intervals would (maybe, I guess) be a little more stable.

**Comment by edsu** [comment]
Ok, that's good to know that the stream is kept open. I guess the organizedata command could gzip stuff as it is moving things around too?

**Comment by edsu** [comment]
I've noticed this with the smaller 15 window too now. Maybe it's related to me running on an ec2 micro instance?
 
Here's what the system looks like when it stops writing the stream files, and is thrashing:

![screen shot 2015-03-14 at 6 28 44 am](https://cloud.githubusercontent.com/assets/33829/6651321/dbb3d734-ca13-11e4-9a2c-7110aca9b22f.png)

and my DATA_DIR:

![screen shot 2015-03-14 at 6 29 40 am](https://cloud.githubusercontent.com/assets/33829/6651325/09c6fd54-ca14-11e4-9cb9-f7812f9eabbe.png)

Notice how a 15 minute file hasn't been written in a while? 

The /var/log/supervisor/supervisord.log doesn't seem to indicate there has been a problem. The last few entries look like

```
015-03-12 17:57:29,536 INFO success: twitterfilter-6 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-03-13 17:35:37,752 INFO exited: twitterfilter-1 (terminated by SIGTERM; not expected)
2015-03-13 17:35:37,875 INFO spawned: 'twitterfilter-1' with pid 18182
2015-03-13 17:35:37,876 INFO exited: twitterfilter-2 (terminated by SIGTERM; not expected)
2015-03-13 17:35:38,232 INFO spawned: 'twitterfilter-2' with pid 18183
2015-03-13 17:35:38,233 INFO exited: twitterfilter-3 (terminated by SIGTERM; not expected)
2015-03-13 17:35:39,305 INFO spawned: 'twitterfilter-3' with pid 18184
2015-03-13 17:35:39,422 INFO success: twitterfilter-2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-03-13 17:35:39,422 INFO success: twitterfilter-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-03-13 17:35:40,499 INFO success: twitterfilter-3 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by dchud** [comment]
Hmm, we are seeing pegged cpu as well, seems likely to be the same problem.

**Comment by edsu** [comment]
Bad news, looks like it is unrelated to running organizedata management command. I disabled the cronjob and it happened again.

**Comment by edsu** [comment]
I tried disabling the writing of gzip encoded streams to see if it might be related to that and the good news   (I guess) is that the same problem happened again. So this problem doesn't appear to be the result of either organizedata or from the gzipping of data.

I'm starting to wonder if `ui.models.RotatingFile` should override `on_status` instead of `on_data`, since [tweepy.streaming.StreamListener](https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L43) now does some things that might be important if Twitter wants to close the stream? It's something I could try out at least to see if it helps.

**Comment by edsu** [comment]
In the process of trying `on_status` I noticed that `RotatingFile` overrides the `StreamListener` but does not call the parent's constructor. I'm running now with a modified version that calls StreamListener.__init__ to see if it might help make this bug go away.

**Comment by dchud** [comment]
@edsu thanks for getting and staying on this!

**Comment by edsu** [comment]
Ran into the same problem even when I called `StreamListener`'s constructor in `RotatingFile.__init__`. *sigh*. I'm starting to wonder if the problem might be in tweepy itself.

**Comment by edsu** [comment]
Good news, my filterstream job has been running fine for almost a week now. The only change I made was to upgrade from tweepy v3.2.0 to v3.4.0. I haven't reviewed their changes but perhaps a bug was introduced somewhere, and they squashed it? I think this at least merits updating sfm's requirements.txt to v3.4.0, then you can close this I think.

**Comment by dchud** [comment]
For @kerchner - test bumping tweepy ahead as per @edsu's suggestion.

**Comment by edsu** [comment]
I've been running several filterstream jobs without a problem for weeks now!
