### ISSUE TITLE
Time is displayed under date column in recent tweets on sfm home page

### ISSUE THREAD

**Issue by rajatvij** [gwu-libraries/social-feed-manager#341]
On SFM Home page, time instead of date is displayed in date column under recent tweets.

Eg.
recent tweets
user 	        date 	rt # 	text
BBCWorld 	03:06:22 	94 	Please turn off your phon...
BBCWorld 	02:45:47 	178 	Egyptian security forces...

**Comment by kerchner** [comment]
Please display both date and time, as recent tweets are likely to all be from the same date

**Comment by rajatvij** [comment]
Here's a little short fix for the issue:
We need to add 
<td>{{ item.date_published|date:"H:i:s m-d-Y" }}</td>
in place of 
<td>{{ item.date_published|date:"H:i:s" }}</td>
in Home.html and we can also change the name of the column to date time. I will incorporate these changes in the fetch_urls branch later today.

**Comment by kerchner** [comment]
Actually, please create a new branch (call it something like
t341-date-column) rather than making the changes in the fetch_urls branch.

**Comment by rajatvij** [comment]
Done. I did the changes and pushed the branch 't341-date-column' on github.
You can check if it works well.

**Comment by kerchner** [comment]
@rajatvij you can go ahead and create a pull request from that branch and assign it to me.
