### ISSUE TITLE
Export all user tweets

### ISSUE THREAD

**Issue by cazzerson** [gwu-libraries/social-feed-manager#351]
Hi,

I may be missing this, but I am hoping that we could add a recurring (cron-based) file export of all user tweets, rather than needing to specify specific users or user sets. Is there a straightforward way of accomplishing this right now?

**Comment by dchud** [comment]
This is a non-obvious use case for us because we track thousands of accounts and dozens of sets.  We do cron-based database backups, rather than data exports, and our exports are almost always user- or set-based.  Can you describe your use case a little more?

It's easy to imagine adding a flag to the export commands but it'd be best to know more about how you would hope to use it... plus we would want to provide useful guidance about large collections.

**Comment by kerchner** [comment]
A workaround right now would be to create a set that includes all of your users.  Logistically, you might dump out all of the "name" values in the ui_twitteruser table and write those to a file, one name per line; then user load_usernames.py to add those all to a new set.  Obviously you'd have to redo this as you add users, so it's not a long term solution.  As @dchud notes above, we have more data than would make sense for a single export, but perhaps your use case lends itself more naturally to that.

**Comment by cazzerson** [comment]
@dchud @kerchner Thanks for responding so quickly. I should have stepped back and described the use case before leaping to a solution. Basically, we've packaged SFM with Lentil and a new web-based configuration tool into the [Social Media Combine](https://github.com/NCSU-Libraries/Social-Media-Combine). This is intended to be a social media harvesting environment that is pre-configured (to the extent that is possible) and easily deployable to personal hardware without advanced IT experience. To that end, in the lentil container we've set [default image and metadata export jobs](https://github.com/NCSU-Libraries/Social-Media-Combine/blob/master/lentil/schedule.rb#L11-L17) so that users of the Combine can easily migrate any harvested content into the long-term storage and management system of their choice. IOW, we're far more focused on [convenience](https://twitter.com/tolloid/status/619230014647730176) than efficiency.

I understand how a bulk export could be a problem with large collections, so I'm curious about other ways to make full (or incrementally complete) exports easier. One simple stopgap solution might be assigning a default user set for all new users. Do you all have any other thoughts about this scenario?

**Comment by bdietz** [comment]
@dchud @kerchner Just to add on to what @cazzerson said. The use case is that, at some interval, we see the need to export the data so we can accession it into the archives, send it through a born digital workflow, and move it into archival storage. So, maybe an export feature would have date, account, and/or tag delimiters, eg, all date by account or hashtag occurring between dates one and two. The exported file could be JSON or a CVS text file.

**Comment by cazzerson** [comment]
In case someone needs a [quick export of all user Tweets](https://gist.github.com/cazzerson/ca92fac571f07d8150edbe43cd2a9b08), I threw something together from existing SFM code.
