### ISSUE TITLE
user stories

### ISSUE THREAD

**Issue by edsu** [gwu-libraries/social-feed-manager#353]
This is kind of a high level question, and could entail a substantial amount of work, but I was wondering if you have talked about modifying SFM so that it is more oriented around the activities of an authenticated (but non-admin) user. So rather than requiring an admin to navigate the admin screens a user could:

1. log in
1. start collecting tweets for a user
1. add that user to a set
1. start collecting tweets for another user
1. add that user to the same set
1. set up their filter stream (I guess there needs to be a quota, since Twitter's API limits it to 2?)
1. see all of these things reflected on their homepage when they log in again
1. be able to view users, sets, filters and users and stop them?

I realize this isn't something that could easily be done, but I was thinking it might be interesting to explore what some of these user stories could look like, and implement them on top of the nice admin functionality you already have.

**Comment by dchud** [comment]
We spent the summer working up user stories just like this.  We should 
be able to publish them all, but I need to run it by the team first.  
I'll take this ticket and close it when I publish.  Thanks @edsu!

**Comment by edsu** [comment]
Looks like this can be closed now because of [this](https://github.com/gwu-libraries/sfm/wiki).

**Comment by dchud** [comment]
:) Thanks again!
