### ISSUE TITLE
export json using management command

### ISSUE THREAD

**Issue by edsu** [gwu-libraries/social-feed-manager#354]
It would be useful to be able to export JSON as you can CSV and Excel.

**Comment by dchud** [comment]
I was just thinking about that.  Should be straightforward.  Thanks!

**Comment by edsu** [comment]
I actually almost have something ready for you to look at using what you already have?

**Comment by dchud** [comment]
A PR would be welcome.  Just a --json flag to the existing command?

**Comment by edsu** [comment]
Yes, and I was going to rename it to export, and remove export_xls?

**Comment by dchud** [comment]
Yeah, we could go a few ways on that... --xls and --csv could be options with --json as the default, or other combinations.  Please just go ahead and submit the PR as you see fit, we will review/discuss at GW next week and continue discussion on the PR itself.

**Comment by edsu** [comment]
okiedoke

**Comment by edsu** [comment]
I guess it would also be nice to be able to download from the UI? But can this ticket just be for the management command?

**Comment by dchud** [comment]
Yeah, let's address those separately. Thanks.



On Jul 10, 2015, at 1:56 PM, Ed Summers <notifications@github.com> wrote:

I guess it would also be nice to be able to download from the UI? But can
this ticket just be for the management command?

—
Reply to this email directly or view it on GitHub
<https://github.com/gwu-libraries/social-feed-manager/issues/354#issuecomment-120494139>
.
