### ISSUE TITLE
filterstream job jammed up

### ISSUE THREAD

**Issue by edsu** [gwu-libraries/social-feed-manager#356]
I've noticed that my filterstream jobs are occasionally getting jammed up, where the `filterstream` management command consumes 100% of the CPU, and it doesn't appear to be writing to the DATA_DIR. 

![screen shot 2015-07-19 at 5 18 11 am](https://cloud.githubusercontent.com/assets/33829/8765349/d352c46c-2dd5-11e5-8a3a-651b8b39d561.png)

![screen shot 2015-07-19 at 5 21 17 am](https://cloud.githubusercontent.com/assets/33829/8765354/013ab8d0-2dd6-11e5-870b-20fc6bf6fb50.png)

The filterstream was quite simple, looking for the hashtag `#disabilitystudies`. At first I thought this might be related to high volume streams, but this one wasn't particularly many tweets (67 in 15 minutes). I am running the latest sfm from master, on a ec2-small instance, Ubuntu 14.04.2 LTS. My cron schedule looks like this:

```
0,15,30,45 * * * * /opt/sfm/scripts/user_timeline.sh
0 22 * * * /opt/sfm/scripts/update_usernames.sh
0 2 * * * /opt/sfm/scripts/fetch_urls.sh
10 15 * * * /opt/sfm/scripts/organizedata.sh
```

`/var/log/sfm/twitterfilter-3.err.log` and `/var/log/sfm/twitterfilter-3.out.log` are empty.  The only thing I see in `/var/log/supervisor/supervisord.log` about the twitterfilter-3 process is:

```
2015-07-15 16:24:53,505 INFO spawned: 'twitterfilter-3' with pid 12850
2015-07-15 16:24:54,993 INFO success: twitterfilter-3 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Deleting the filterstream from SFM admin terminates the process and the CPU usage goes back down to normal. Has anyone noticed this sort of behavior before, or have any ideas what might be causing it?

One last thing of note: I noticed that the last file that was written to by the `filterstream` management command was moved by the `organizedata` management command, and that it has 0 bytes. 

```
ubuntu@ip-172-30-1-141:~$ ls -l /mnt/sfm/twitterfilter-3/2015/07/16/14
total 32
-rw-r--r-- 1 ubuntu ubuntu 30703 Jul 16 14:20 twitterfilter-3-2015-07-16T14-05-30Z.gz
-rw-r--r-- 1 ubuntu ubuntu     0 Jul 16 14:20 twitterfilter-3-2015-07-16T14-20-36Z.gz
```

I wonder if there could be some strange interaction between `filterstream` and `organizedata` here? Perhaps `organizedata` is moving files around while `filterstream` is closing it, or something? Do you typically put `organizedata` in cron? Anyhow, sorry for the length of this ticket. This has happened to me several times now so I thought it was worth at least raising it.

**Comment by edsu** [comment]
This happened again with only one filterstream running. I tried to use strace to see what the process might be doing while consuming 100% of the CPU, and it appears to be doing nothing at the system level:

```
ubuntu@ip-172-30-1-141:/mnt/sfm/twitterfilter-1$ ps -ef |grep python
root     15014     1  0 Jul10 ?        00:22:57 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
www-data 19204 15014 53 Jul16 ?        6-22:25:04 /opt/sfm/ENV/bin/python /opt/sfm/sfm/manage.py filterstream 1 --save
ubuntu   26277 26130  0 15:31 pts/0    00:00:00 grep --color=auto python
ubuntu@ip-172-30-1-141:/mnt/sfm/twitterfilter-1$ sudo strace -p 19204
Process 19204 attached
```

It just sits like that with no output forever, or at least 15 minutes.

**Comment by dchud** [comment]
It seems likely that your hunch about ```organizedata``` moving files around before ```filterstream``` is done is on the right track.  It might be worth trying tweaking the timing of your ```organizedata``` runs and the timing of ```filterstream``` file closes.

See also #171 and #316.

**Comment by edsu** [comment]
I guess this really is a duplicate of #316 ; closing.
