### ISSUE TITLE
When deploying a new release, active twitterfilters need to be migrated

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/social-feed-manager#379]
In the documented deployment/upgrade process, we haven't explicitly accounted for the fact that SFM writes a configuration file into sfm/sfm/supervisor.d for each active twitterfilter.  Merely copying the database will not bring over the active twitterfilter configuration files.  Moreover, these supervisor process configuration files contain explicit references to the path of the application, which may change upon new deployment.

A workaround is to go into the application/admin and deactivate/reactivate each active twitterfilter, to rewrite the config files.  However, a better solution could be developed.

**Comment by dchud** [comment]
Maybe just a management command to create confs for all active filters and a note in the install?

**Comment by kerchner** [comment]
:+1:

**Comment by kerchner** [comment]
Actually, this is taken care of by running ```./manage.py createconf``` which is present in the deployment notes.  Closing this ticket.
