### ISSUE TITLE
In documentation, add links to archived social media platforms' data dictionaries

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/social-feed-manager#383]
E.g., http://sfm.readthedocs.io/en/latest/data_dictionary.html could link to:

Twitter API documentation - https://web.archive.org/web/*/https://dev.twitter.com/docs
Tweets - https://web.archive.org/web/*/https://dev.twitter.com/overview/api/tweets (this may have had an alternate URL before January 2015)
Entities - https://dev.twitter.com/docs/platform-objects/entities

**Comment by kerchner** [comment]
@reliztrent I think you meant to open this on the https://github.com/gwu-libraries/sfm-ui repo.  Please close and create a copy over there.
